# syntax=docker/dockerfile:1
FROM registry.fedoraproject.org/fedora:43

WORKDIR /tmp/sunshine
COPY --link scripts/linux_build.sh ./scripts/linux_build.sh

RUN <<_DEPS
#!/bin/bash
set -e
chmod +x ./scripts/linux_build.sh
TMPDIR=/var/tmp ./scripts/linux_build.sh \
  --step=deps \
  --sudo-off \
  --skip-cuda

dnf clean all
rm -rf /var/cache/dnf
rm -rf /tmp/sunshine
_DEPS

ENV HOME=/root
WORKDIR /workspaces/Sunshine
